---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: content/impostazioni_contatti.md
  label: Impostazioni e Contatti
- type: document
  path: content/pages/home.md
  label: Home
- type: document
  path: content/pages/news.md
  label: News
- type: directory
  path: content/collections
  label: Collections
  create: documents
  match: "**/*"
  templates:
  - collection
- type: directory
  path: content/posts
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - post
upload_dir: content/images
public_path: "/content/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn build
